<FavoritesScreen>:
    RecycleView:
        id: rv
        key_viewclass: 'viewclass'
        do_scroll_x: False
        always_overscroll: False
        smooth_scroll_end: 10

        RecycleBoxLayout:
            default_size: None, dp(65)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            spacing: '2dp'
            orientation: 'vertical'
        # RecycleBoxLayout
    # RecycleView