<MainCard>:
    x: 0
    y: 0
    size_hint: (1, 1)
    orientation: 'vertical'

    # Toolbar
    MDBoxLayout:
        adaptive_height: True
        orientation: 'horizontal'
        spacing: '10dp'

        MDIconButton:
            icon: 'menu'
        # MDIconButton

        MDLabel:
            text: 'Music'
            bold: True
            font_size: '20sp'
        # MDLabel
    # MDBoxLayout # Toolbar
# MainCard
