name: Android Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3


       - name: Build with Buildozer
         uses: ArtemSBulgakov/buildozer-action@v1
         id: buildozer
         with:
           command: buildozer android debug
           buildozer_version: stable
      
       - uses: jungwinter/split@v2
         id: split
         with:
           msg: ${{ steps.buildozer.outputs.filename }}
           separator: "/"

        
       - name: Upload artifacts
         uses: actions/upload-artifact@v2
         with:
           name: ${{ steps.split.outputs._1}}
           path: ${{ steps.buildozer.outputs.filename }}
      
